### PR TITLE
add austin - based off stus add seattle branch

### PR DESCRIPTION
**Pull request by BooneTeam**
Please Add Austin 🐰

### CODE REVIEW

**Comment by alycit** [comment]
@BooneTeam Thanks for this.  I'm going to do a little work over the break on this an a couple of other PRs as well.  I heard that there was a bug in the homepage filtering with Seattle still showing up when you filter the list, so I want to make sure that doesn't impact you either!

**Comment by BooneTeam** [comment]
Nice, thanks for takin a look and fixin the bugs! :)

**Comment by wh1tney** [comment]
@alycit safe to merge?

**Comment by alycit** [comment]
@BooneTeam Merged and Deployed.

**Comment by wh1tney** [comment]
@alycit @BooneTeam thank you! 🙏

**Pull request merged**
