### PR TITLE
Making public/promote's location dynamic

### PR DESCRIPTION
**Pull request by redsquirrel**
Append the location onto the URL, like `?chicago` or `?sf` or `?nyc`. The page will use that query string to filter mentoring availabilities.

### CODE REVIEW

**Comment by ltw** [comment]
Is this still relevant? Can we merge this?

**Comment by ltw** [comment]
Actually, we're about to start working on tabs for location. Should we abandon this in favor of #99?

**Comment by alycit** [comment]
Closing since we have the filter drop down now.

**Comment by redsquirrel** [comment]
It makes me 😃  that this app is still helping students connect with mentors. ❤️ ❤️ ❤️

**Pull request closed without merging**
