### PR TITLE
Fix email format errors by expecting flat text email only.

### PR DESCRIPTION
**Pull request by secade**
I believe this should address the error reported in issue 145.

Since the email format looks to be text only and isn't rendering the html appropriately, just set it to make sense with straight text. This is in line with the other email templates in the application.

### CODE REVIEW

**Comment by ltw** [comment]
Build failure, please address.

**Comment by secade** [comment]
Whoops, forgot to check the build earlier... should be resolved now.

**Comment by secade** [comment]
Looks like it finally built green @ltw `yay`

**Comment by ltw** [comment]
:+1: merging.

**Pull request merged**
